[tool.poetry]
name = "triflingflashysearch"
version = "0.1.0"
description = ""
authors = ["Honglin Bao <baohlcs@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
keras = "^2.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
